# Generated by Django 2.2.2 on 2020-04-14 15:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bioseq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('resolution', models.FloatField(default=20)),
                ('experiment', models.CharField(max_length=100, null=True)),
                ('deprecated', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('text', models.TextField()),
                ('taxon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structures', to='bioseq.Taxon')),
            ],
            options={
                'unique_together': {('code', 'deprecated')},
            },
        ),
        migrations.CreateModel(
            name='PDBResidueSet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('pdb', models.ForeignKey(db_column='pdb_id', on_delete=django.db.models.deletion.CASCADE, related_name='residue_sets', to='pdbdb.PDB')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='PropertyTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('property', models.ForeignKey(db_column='residue_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tags', to='pdbdb.Property')),
            ],
            options={
                'unique_together': {('property', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='Residue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chain', models.CharField(max_length=20)),
                ('resname', models.CharField(max_length=4)),
                ('resid', models.IntegerField()),
                ('icode', models.CharField(default='', max_length=2)),
                ('type', models.CharField(max_length=10)),
                ('disordered', models.BooleanField(default=False)),
                ('modelable', models.BooleanField(default=True)),
                ('seq_order', models.IntegerField(null=True)),
                ('pdb', models.ForeignKey(db_column='pdb_id', on_delete=django.db.models.deletion.CASCADE, related_name='residues', to='pdbdb.PDB')),
            ],
            options={
                'unique_together': {('pdb', 'chain', 'resid', 'icode', 'type')},
            },
        ),
        migrations.CreateModel(
            name='ResidueSetResidue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pdbresidue_set', models.ForeignKey(db_column='pdbresidueset_id', on_delete=django.db.models.deletion.CASCADE, related_name='residue_set_residue', to='pdbdb.PDBResidueSet')),
                ('residue', models.ForeignKey(db_column='residue_id', on_delete=django.db.models.deletion.CASCADE, related_name='residue_sets', to='pdbdb.Residue')),
            ],
            options={
                'unique_together': {('residue', 'pdbresidue_set')},
            },
        ),
        migrations.CreateModel(
            name='ResidueSet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'unique_together': {('name',)},
            },
        ),
        migrations.AddField(
            model_name='pdbresidueset',
            name='residue_set',
            field=models.ForeignKey(db_column='residueset_id', on_delete=django.db.models.deletion.CASCADE, related_name='residuesets', to='pdbdb.ResidueSet'),
        ),
        migrations.CreateModel(
            name='Atom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serial', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('altLoc', models.CharField(default=' ', max_length=1)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('occupancy', models.FloatField()),
                ('bfactor', models.FloatField()),
                ('anisou', models.FloatField(null=True)),
                ('element', models.CharField(max_length=10)),
                ('residue', models.ForeignKey(db_column='residue_id', on_delete=django.db.models.deletion.CASCADE, related_name='atoms', to='pdbdb.Residue')),
            ],
        ),
        migrations.CreateModel(
            name='ResidueSetProperty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField(null=True)),
                ('pdbresidue_set', models.ForeignKey(db_column='pdbresidueset_id', on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='pdbdb.PDBResidueSet')),
                ('property', models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='residuesets', to='pdbdb.Property')),
                ('tag', models.ForeignKey(db_column='propertytag_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='residue_sets', to='pdbdb.PropertyTag')),
            ],
            options={
                'unique_together': {('pdbresidue_set', 'property', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='ResidueProperty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField(null=True)),
                ('property', models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.DO_NOTHING, to='pdbdb.PDB')),
                ('residue', models.ForeignKey(db_column='residue_id', on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='pdbdb.Residue')),
                ('tag', models.ForeignKey(db_column='propertytag_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='residues', to='pdbdb.PropertyTag')),
            ],
            options={
                'unique_together': {('residue', 'property', 'tag')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='pdbresidueset',
            unique_together={('pdb', 'residue_set', 'name')},
        ),
        migrations.CreateModel(
            name='PDBProperty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField(null=True)),
                ('pdb', models.ForeignKey(db_column='pdb_id', on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='pdbdb.PDB')),
                ('property', models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.DO_NOTHING, to='pdbdb.PDB')),
                ('tag', models.ForeignKey(db_column='propertytag_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pdbs', to='pdbdb.PropertyTag')),
            ],
            options={
                'unique_together': {('pdb', 'property', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='ChainProperty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chain', models.CharField(max_length=10)),
                ('value', models.FloatField(null=True)),
                ('pdb', models.ForeignKey(db_column='pdb_id', on_delete=django.db.models.deletion.CASCADE, related_name='chain_props', to='pdbdb.PDB')),
                ('property', models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='chains', to='pdbdb.Property')),
                ('tag', models.ForeignKey(db_column='propertytag_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='chains', to='pdbdb.PropertyTag')),
            ],
            options={
                'unique_together': {('pdb', 'chain', 'property', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='AtomResidueSet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('atom', models.ForeignKey(db_column='atom_id', on_delete=django.db.models.deletion.CASCADE, to='pdbdb.Atom')),
                ('pdb_set', models.ForeignKey(db_column='residuesetresidue_id', on_delete=django.db.models.deletion.CASCADE, related_name='atoms', to='pdbdb.ResidueSetResidue')),
            ],
            options={
                'unique_together': {('pdb_set', 'atom')},
            },
        ),
        migrations.CreateModel(
            name='AtomProperty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField(null=True)),
                ('atom', models.ForeignKey(db_column='atom_id', on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='pdbdb.Atom')),
                ('property', models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='atoms', to='pdbdb.Property')),
                ('tag', models.ForeignKey(db_column='propertytag_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='atoms', to='pdbdb.PropertyTag')),
            ],
            options={
                'unique_together': {('atom', 'property', 'tag')},
            },
        ),
    ]
